
<html lang="en">

  <?php include 'head.phtml'?>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <?php include 'header.phtml'?>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <?php include 'navbar.phtml'?>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
          </div>


          <!-- Content Row -->
<div class="col-md-12">
  <div class="form-group">
    <label for="exampleFormControlSelect1">Example select</label>
    <select class="form-control" id="uye">
      <?php for ($i=0; $i < count($user); $i++) { ?>

      <option value="<?=$user[$i]->id?>"><?=$user[$i]->name.' '.$user[$i]->surname.'-'.$user[$i]->email.'-'?></option>
<?php       } ?>
    </select>
    </div>
    <button class="btn btn-success" onclick="submit()">yetki ver </button>
</div>
<br>
<hr>
<br>
<div class="col-sm-12"><table class="table table-bordered dataTable" id="dataTable" role="grid" aria-describedby="dataTable_info" style="width: 100%;" width="100%" cellspacing="0">
                  <thead>
                  <tr><th rowspan="1" colspan="1">İsim</th> <th rowspan="1" colspan="1">yetki</th><th rowspan="1" colspan="1">işlemler</th></tr>
                  </thead>
                  <tfoot>
                  <tr><th rowspan="1" colspan="1">İsim</th> <th rowspan="1" colspan="1">yetki</th><th rowspan="1" colspan="1">işlemler</th></tr>
                  </tfoot>
                  <tbody>
                  <?php for ($i=0; $i <count($adminuser) ; $i++) { ?>

                  <tr role="row" class="odd">
                      <td class="sorting_1"><?=$adminuser[$i]->name.' '.$adminuser[$i]->surname?></td>
                      <th rowspan="1" colspan="1">
                      <?php if ($adminuser[$i]->status==2) { ?>
                        <a style="color:green">admin</a>
                      <?php }else{?>
                        <a style="color:red">kullanıcı</a>
                      <?php }?>
                      </th>
                      <td>
                      <button onclick="deletepost(<?=$adminuser[$i]->id?>)">Yetki al</button>
                      </td>
                      </tr>

<?php              } ?>

                    </tbody>
                </table>
                </div>


        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <?php include 'script.phtml'?>
  <script>
  function submit() {
    var param=$("#uye").val();
    $.ajax({
              url: '<?=$url?>/admin/authorization/submit/'+param,
              type: 'get',
              contentType: false,
              processData: false,
              success: function(response){
                  if(response.success == "ok"){
                        alert("YETKİ VERİLDİ");
                          window.location.reload(false);
                  }else{
                      alert("YETKİ VERİLEMEDİ");
                  }
              },
          });
      
  };
  function deletepost(param) {
    $.ajax({
              url: '<?=$url?>/admin/authorization/delete/'+param,
              type: 'get',
              contentType: false,
              processData: false,
              success: function(response){
                  if(response.success == "ok"){
                        alert("UYENİN YETKİSİ KALDIRILDI");
                          window.location.reload(false);
                  }else{
                      alert("UYE YETKİSİ KALDIRILAMADI");
                  }
              },
          });
      
  };
  </script>

</body>

</html>
