<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="index.html">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Interface
      </div>
      < <li class="nav-item">
        <a class="nav-link" href="<?=$url?>/admin/post">
          <i class="fas fa-fw fa-table"></i>
          <span>Post  işlemleri</span></a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="<?=$url?>/admin/comment">
          <i class="fas fa-fw fa-table"></i>
          <span>Yotum işlemleri</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<?=$url?>/admin/authorization">
          <i class="fas fa-fw fa-table"></i>
          <span>Yetki işlemleri</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<?=$url?>/admin/user">
          <i class="fas fa-fw fa-table"></i>
          <span>Kullanıcı işlemleri</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<?=$url?>/admin/category">
          <i class="fas fa-fw fa-table"></i>
          <span>kategori işlemleri</span></a>
      </li>
      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" href="<?=$url?>/admin/question-category">
          <i class="fas fa-fw fa-table"></i>
          <span>Soru cevap kategori işlemleri</span></a>
      </li>


      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>