<!DOCTYPE html>
<html lang="en">

  <?php include 'head.phtml'?>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <?php include 'header.phtml'?>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <?php include 'navbar.phtml'?>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
          </div>


          <!-- Content Row -->

          <div class="col-sm-12"><table class="table table-bordered dataTable" id="dataTable" role="grid" aria-describedby="dataTable_info" style="width: 100%;" width="100%" cellspacing="0">
                  <thead>
                  <tr><th rowspan="1" colspan="1">İsim</th> <th rowspan="1" colspan="1">İsim</th><th rowspan="1" colspan="1">tarih</th><th rowspan="1" colspan="1">Yazar</th><th rowspan="1" colspan="1">tarih</th><th rowspan="1" colspan="1">işlemler</th></tr>
                  </thead>
                  <tfoot>
                    <tr><th rowspan="1" colspan="1">İsim</th> <th rowspan="1" colspan="1">İsim</th><th rowspan="1" colspan="1">tarih</th><th rowspan="1" colspan="1">Yazar</th><th rowspan="1" colspan="1">tarih</th><th rowspan="1" colspan="1">işlemler</th></tr>
                  </tfoot>
                  <tbody>
                  <?php for ($i=0; $i <count($post) ; $i++) { ?>

                  <tr role="row" class="odd">
                      <td class="sorting_1"><?=$post[$i]->title?></td>
                      <th rowspan="1" colspan="1">
                      <?php if ($post[$i]->status==1) { ?>
                        <a style="color:green">onaylandı</a>
                      <?php }else{?>
                        <a style="color:red">onay bekliyor</a>
                      <?php }?>
                      
                      </th>
                      <td class="sorting_1"><?=$post[$i]->date?></td>
                      <td class="sorting_1"><?=$post[$i]->name.' '.$post[$i]->surname?></td>
                      <td class="sorting_1"><?=$post[$i]->category_name?></td>
                      <td>
                      <button onclick="submit(<?=$post[$i]->id?>)">onayla</button>
                      <button onclick="deletepost(<?=$post[$i]->id?>)">silme</button>
                      <button ><a href="<?=$url?>/admin/preview/<?=$post[$i]->id?>"  target="_blank">incele</a></button>                      
                      </td>
                      </tr>

<?php              } ?>

                    </tbody>
                </table>
                </div>

     


        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <?php include 'script.phtml'?>
  <script>
  function submit(param) {
    $.ajax({
              url: '<?=$url?>/admin/post/submit/'+param,
              type: 'get',
              contentType: false,
              processData: false,
              success: function(response){
                  if(response.success == "ok"){
                        alert("YAZI ONAYLANDI");
                          window.location.reload(false);
                  }else{
                      alert("YAZI ONAYLANMANDI");
                  }
              },
          });
      
  };
  function deletepost(param) {
    $.ajax({
              url: '<?=$url?>/admin/post/delete/'+param,
              type: 'get',
              contentType: false,
              processData: false,
              success: function(response){
                  if(response.success == "ok"){
                        alert("YAZI SİLİNDİ");
                          window.location.reload(false);
                  }else{
                      alert("YAZI SİLİNEMEDİ");
                  }
              },
          });
      
  };
  </script>


</body>

</html>
