<!DOCTYPE html>
<html lang="en">

  <?php include 'head.phtml'?>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <?php include 'header.phtml'?>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <?php include 'navbar.phtml'?>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
          </div>


          <!-- Content Row -->

          
           <div class="form-group">
             <label for="exampleInputEmail1">Soru cevap Kategori Ekle</label>
             <input type="text" class="form-control" id="name"  placeholder="kategori adı">
           </div>
           <button type="submit" onclick="add()" class="btn btn-primary">Submit</button>
          
        <hr>

          <div class="col-sm-12"><table class="table table-bordered dataTable" id="dataTable" role="grid" aria-describedby="dataTable_info" style="width: 100%;" width="100%" cellspacing="0">
                  <thead>
                  <tr><th rowspan="1" colspan="1">İsim</th><th rowspan="1" colspan="1">işlemler</th></tr>
                  </thead>
                  <tfoot>
                    <tr><th rowspan="1" colspan="1">İsim</th><th rowspan="1" colspan="1">işlemler</th></tr>
                  </tfoot>
                  <tbody>
                  <?php for ($i=0; $i <count($category) ; $i++) { ?>

                  <tr role="row" class="odd">
                      <td class="sorting_1"><?=$category[$i]->category_name?></td>
                      <td>
                      <button onclick="deletepost(<?=$category[$i]->id?>)">silme</button>
                      <button  onclick="update(<?=$category[$i]->id?>)">güncelleme</button>                      
                      </td>
                      </tr>

<?php              } ?>

                    </tbody>
                </table>
                </div>


        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <?php include 'script.phtml'?>
<script>

function deletepost(param) {
    $.ajax({
              url: '<?=$url?>/admin/question-category/delete/'+param,
              type: 'get',
              contentType: false,
              processData: false,
              success: function(response){
                  if(response.success == "ok"){
                        alert("KATEGORİ SİLİNDİ");
                          window.location.reload(false);
                  }else{
                      alert("KATEGORİ SİLİNEMEDİ");
                  }
              },
          });
      
  };
  function add(){
    var data="name="+$('#name').val();
    $.ajax({
              url: '<?=$url?>/admin/question-category/add,
              type: 'post',data:data,
              success: function(response){
                  if(response.success == "ok"){
                        alert("KATEGORİ eklendi");
                          window.location.reload(false);
                  }else{
                      alert("KATEGORİ eklenemedi");
                  }
              },
          });
    
  }
</script>

</body>

</html>
