<!DOCTYPE html>
<html lang="en">

  <?php include 'head.phtml'?>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <?php include 'header.phtml'?>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <?php include 'navbar.phtml'?>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>

          </div>


          <!-- Content Row -->

          <div class="col-sm-12"><table class="table table-bordered dataTable" id="dataTable" role="grid" aria-describedby="dataTable_info" style="width: 100%;" width="100%" cellspacing="0">
                  <thead>
                  <tr><th rowspan="1" colspan="1">İsim-soyisim</th><th rowspan="1" colspan="1">resimler</th></tr>
                  </thead>
                  <tfoot>
                  <tr><th rowspan="1" colspan="1">İsim-soyisim</th><th rowspan="1" colspan="1">resimler</th></tr
                  </tfoot>
                  <tbody>
                  <?php for ($i=0; $i <count($user) ; $i++) { ?>

                  <tr role="row" class="odd">
                      <td class="sorting_1"><?=$user[$i]->name.' '.$user[$i]->surname?></td>
                      <td>
                      <img src="<?=$url?>/templates/images/<?=$user[$i]->image?>" class="img-thumbnail" />                      
                      </td>
                      </tr>

<?php              } ?>

                    </tbody>
                </table>
                </div>

     


        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <?php include 'script.phtml'?>


</body>

</html>
