
<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300, 400,700|Inconsolata:400,700" rel="stylesheet">

<link rel="stylesheet" href="<?=$url?>/templates/css/bootstrap.css">
<link rel="stylesheet" href="<?=$url?>/templates/css/animate.css">
<link rel="stylesheet" href="<?=$url?>/templates/css/owl.carousel.min.css">

<link rel="stylesheet" href="<?=$url?>/templates/fonts/ionicons/css/ionicons.min.css">
<link rel="stylesheet" href="<?=$url?>/templates/fonts/fontawesome/css/font-awesome.min.css">
<link rel="stylesheet" href="<?=$url?>/templates/fonts/flaticon/font/flaticon.css">

<!-- Theme Style -->
<link rel="stylesheet" href="<?=$url?>/templates/css/style.css">