<div class="col-md-12 col-lg-4 sidebar">
    <div class="sidebar-box search-form-wrap">
        <form action="#" class="search-form">
            <div class="form-group">
                <span class="icon fa fa-search"></span>
                <input type="text" class="form-control" id="s" placeholder="Type a keyword and hit enter">
            </div>
        </form>
    </div>
    <!-- END sidebar-box -->

    <!-- END sidebar-box -->
    <div class="sidebar-box">
        <h3 class="heading">Popular Posts</h3>
        <div class="post-entry-sidebar">
            <ul>
                <?php
                for ($i=0;$i<count($popular);$i++){?>
                    <li>
                        <a href="<?=$url?>/article/<?=$popular[$i]->sef_link?>">
                            <img src="<?=$url?>/templates/images/<?=$popular[$i]->image?>" alt="Image placeholder" class="mr-4">
                            <div class="text">
                                <h4><?=$popular[$i]->title?></h4>
                                <div class="post-meta">
                                    <span class="mr-2"><?=$popular[$i]->date?></span>
                                </div>
                            </div>
                        </a>
                    </li>
                <?php } ?>


            </ul>
        </div>
    </div>
    <!-- END sidebar-box -->
</div>
