<script src="<?=$url?>/templates/js/jquery-3.2.1.min.js"></script>
<script src="<?=$url?>/templates/js/jquery-migrate-3.0.0.js"></script>
<script src="<?=$url?>/templates/js/popper.min.js"></script>
<script src="<?=$url?>/templates/js/bootstrap.min.js"></script>
<script src="<?=$url?>/templates/js/owl.carousel.min.js"></script>
<script src="<?=$url?>/templates/js/jquery.waypoints.min.js"></script>
<script src="<?=$url?>/templates/js/jquery.stellar.min.js"></script>
<script src="<?=$url?>/templates/js/main.js"></script>