<!doctype html>
<html lang="en">
  <head>
    <title>Colorlib Wordify &mdash; Minimal Blog Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php include "component/head.phtml" ?>
  </head>
  <body>
    

    <div class="wrap">

        <?php include "component/header.phtml" ?>
      <!-- END header -->
<?php if (count($slider)!=0) { ?>
      <section class="site-section pt-5 pb-5">
        <div class="container">
          <div class="row">
            <div class="col-md-12">

              <div class="owl-carousel owl-theme home-slider">

              <?php for ($i=0; $i < count($slider); $i++) {  ?>
                <div>
                  <a href="<?=$url?>/article/<?=$slider[$i]->sef_link?>" class="a-block d-flex align-items-center height-lg" style="background-image: url('<?=$url?>/templates/images/<?=$slider[$i]->img?>'); ">
                    <div class="text half-to-full">
                      <span class="category mb-5"><?=$slider[$i]->category_name?></span>
                      <div class="post-meta">
                        
                        <span class="author mr-2"><img src="<?=$url?>/templates/images/<?=$slider[$i]->image?>" alt="Colorlib"> <?=$slider[$i]->name.' '.$slider[$i]->surname ?></span>&bullet;
                        <span class="mr-2"><?=$slider[$i]->date?></span> &bullet;

                        
                      </div>
                      <h3><?=$slider[$i]->title?></h3>
                      <p><?=$slider[$i]->text?></p>
                    </div>
                  </a>
                </div>

              <?php }?>
              </div>
            </div>
          </div>
        </div>


      </section>
              <?php } ?>
      <!-- END section -->

      <section class="site-section py-sm">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <h2 class="mb-4">Latest Posts</h2>
            </div>
          </div>
          <div class="row blog-entries">
            <div class="col-md-12 col-lg-8 main-content">
              <div class="row">
                <?php for ($i=0;$i<count($post);$i++){ ?>
                    <div class="col-md-6">
                        <a href="<?=$url?>/article/<?=$post[$i]->sef_link?>" class="blog-entry element-animate" data-animate-effect="fadeIn">
                            <img src="<?=$url?>/templates/images/<?=$post[$i]->img?>" alt="Image placeholder">
                            <div class="blog-content-body">
                                <div class="post-meta">
                                    <span class="mr-2"><?=$post[$i]->date?></span> &bullet;
                                    <span class="author mr-2"><img src="<?=$url?>/templates/images/<?=$post[$i]->image?>" alt="Colorlib"> <?=$post[$i]->name.' '.$post[$i]->surname ?></span>
                                </div>
                                <h2><?=$post[$i]->title?></h2>
                            </div>
                        </a>
                    </div>
                 <?php }?>

              </div>

              <div class="row mt-5">
                <div class="col-md-12 text-center">
                  <nav aria-label="Page navigation" class="text-center">
 <ul class="pagination">
                      <li class="page-item  active"><a class="page-link" href="#">&lt;</a></li>
                        <?php
                        for ($i=0;$i<$len;$i++){?>
                      <li class="page-item"><a class="page-link" href="<?=$url?>/page/<?=$i?>"><?=$i?></a></li>
                        <?php }?>

                    </ul>
                  </nav>
                </div>
              </div>


              

              

            </div>
              <?php include "component/leftbar.phtml" ?>
            <!-- END main-content -->


            <!-- END sidebar -->

          </div>
        </div>
      </section>

        <?php include "component/footer.phtml" ?>
      <!-- END footer -->

    </div>
    
    <!-- loader -->



    <?php include "component/script.phtml" ?>

  </body>
</html>