
<!doctype html>
<html lang="en">
  <head>
    <title>Colorlib Wordify &mdash; Minimal Blog Template</title>
      <?php include 'component/head.phtml'?>
  </head>
  <body>
    

    <div class="wrap">
        <?php include 'component/header.phtml'?>
      <!-- END header -->

    <section class="site-section py-lg">
      <div class="container">
        
        <div class="row blog-entries element-animate">

          <div class="col-md-12 col-lg-12 main-content">
                <div id="alert"></div>

                  <div class="form-group">
                      <label for="exampleFormControlInput1">Article Title</label>
                      <input type="text" class="form-control" id="title" placeholder="title">
                  </div>
                  <div class="form-group">
                      <label for="exampleFormControlSelect1">Category</label>
                      <select class="form-control" id="category">
                         <?php for ($i=0;$i<count($category);$i++){ ?>
                          <option value="<?=$category[$i]->category_id?>"><?=$category[$i]->category_name?></option>
                        <?php }?>
                      </select>
                  </div>

                  <div class="form-group">
                      <label for="exampleFormControlTextarea1">Article text</label>
                      <textarea class="form-control" id="text" rows="10"></textarea>
                  </div>

                  <div class="row ">
                      <div class="col-md-12">
                          <input type="file" class="custom-file-input" onchange="upload()" id="validatedCustomFile" accept="image/*" required>
                          <label id="label" class="custom-file-label" for="validatedCustomFile">Choose image...</label>
                      </div>


                  </div>
              <br>
              <div class="form-group">
                  <input type="hidden" id="link">
                  <img src="" id="image" >
              </div>
                  <div class="form-group">
                      <input type="button" onclick="save()" class="btn btn-success" value="send">
                  </div>

          </div>

          <!-- END main-content -->
          <!-- END sidebar -->

        </div>
      </div>
    </section>


    <!-- END section -->

        <?php include 'component/footer.phtml'?>
      <!-- END footer -->

    </div>
    
    <!-- loader -->
    <?php
    include 'component/script.phtml'; ?>
  <script src="<?=$url?>/templates/js/ckeditor/ckeditor.js"></script>
  <script>

      CKEDITOR.replace( 'text' );
      function upload() {

          var fd = new FormData();
          var files = $('#validatedCustomFile')[0].files[0];
          $('#label').text(files.name);
          fd.append('file',files);
          $.ajax({
              url: '<?=$url?>/upload-photo',
              type: 'post',
              data: fd,
              contentType: false,
              processData: false,
              success: function(response){
                  if(response.success == "ok"){

                      $('#image').attr("src","<?=$url?>/templates/images/"+response.file);
                      $("#link").val(response.file);
                      $("#alert").html('<div class="alert alert-success alert-dismissible fade show">\n' +
                          '    <strong>Başarılı!</strong> resim yüklendi.\n' +
                          '    <button type="button" class="close" data-dismiss="alert">&times;</button>\n' +
                          '</div>');
                  }else{
                      alert('file not uploaded');
                  }
              },
          });
      }
      function save() {
          var title=$("#title").val();
          var text1=CKEDITOR.instances.text.getData();
          var category=$("#category").val();
          var image=$("#link").val();
          if(title !=""&&text1!=""&&category!=""&&image!=""){
          var data="title="+title+"&text="+text1+"&category="+category+"&image="+image;
          $.ajax({
              url: '<?=$url?>/new-article',
              type: 'post',
              data: data,
              success: function(response){
                  if(response.success == "ok"){
                     alert("yazı moderator onayından sonra yayına alınacaktır");
                     window.reload();
                  }else{
                      alert('file not uploaded');
                  }
              },
          })}else {
              alert("boş alan bırakılamaz.")
          }
      }
  </script>
  </body>
</html>