
<!doctype html>
<html lang="en">
  <head>
    <title>Colorlib Wordify &mdash; Minimal Blog Template</title>
      <?php include 'component/head.phtml'?>
  </head>
  <body>
    

    <div class="wrap">
        <?php include 'component/header.phtml'?>
      <!-- END header -->

    <section class="site-section py-lg">
      <div class="container">
        
        <div class="row blog-entries element-animate">

          <div class="col-md-12 col-lg-12 main-content">
                <div id="alert"></div>

                  <div class="form-group">
                      <label for="exampleFormControlInput1">Question Title</label>
                      <input type="text" class="form-control" id="title" placeholder="name@example.com">
                  </div>
                  <div class="form-group">
                      <label for="exampleFormControlSelect1">Category</label>
                      <select class="form-control" id="category">
                         <?php for ($i=0;$i<count($qcategory);$i++){ ?>
                          <option value="<?=$qcategory[$i]->id?>"><?=$qcategory[$i]->category_name?></option>
                        <?php }?>
                      </select>
                  </div>

                  <div class="form-group">
                      <label for="exampleFormControlTextarea1">Question text</label>
                      <textarea class="form-control" id="text" rows="10"></textarea>
                  </div>
                  </div>
              <br>
                  <div class="form-group">
                      <input type="button" onclick="save()" class="btn btn-success" value="send">
                  </div>

          </div>

          <!-- END main-content -->
          <!-- END sidebar -->

        </div>
      </div>
    </section>


    <!-- END section -->

        <?php include 'component/footer.phtml'?>
      <!-- END footer -->

    </div>
    
    <!-- loader -->
    <?php
    include 'component/script.phtml'; ?>
  <script src="<?=$url?>/templates/js/ckeditor/ckeditor.js"></script>
  <script>

      CKEDITOR.replace( 'text' );
      function save() {
          var title=$("#title").val();
          var text1=CKEDITOR.instances.text.getData();
          var category=$("#category").val();
          if(title !=""&&text1!=""&&category!=""){
          var data="title="+title+"&text="+text1+"&category="+category;
          $.ajax({
              url: '<?=$url?>/new-question',
              type: 'post',
              data: data,
              success: function(response){
                  if(response.success == "ok"){
                     alert("sorunuz  yayına alınmıştır");
                     window.reload();
                  }else{
                      alert('file not uploaded');
                  }
              },
          })}else {
              alert("boş alan bırakılamaz.")
          }
      }
  </script>
  </body>
</html>