
<!doctype html>
<html lang="en">
  <head>
    <title>Colorlib Wordify &mdash; Minimal Blog Template</title>
      <?php include 'component/head.phtml'?>
  </head>
  <body>
    

    <div class="wrap">

    <?php include 'component/header.phtml'?>
      <!-- END header -->

      <!-- END section -->

      <section class="site-section py-sm">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <h2 class="mb-4">Latest Posts</h2>
            </div>
          </div>
          <div class="row blog-entries">
            <div class="col-md-12 col-lg-8 main-content">
              <div class="row">

                  <?php
                  for ($i=0;$i<count($post);$i++){?>
                      <div class="col-md-12">
                          <a href="<?=$url?>/question-answer/<?=$post[$i]->question_sef_link?>" class="blog-entry element-animate" data-animate-effect="fadeIn">
                              <div class="blog-content-body">
                                  <div class="post-meta">
                                      <span class="mr-2"> <?=$post[$i]->date?></span> &bullet;
                                      <span class="mr-2" onclick="window.location='<?=$url?>/question-answer/category/<?=$post[$i]->sef_link?>'"><?=$post[$i]->category_name?></span> &bullet;
                                      <h2><?=$post[$i]->title?></h2>
                                  </div>

                              </div>
                          </a>
                      </div>
                  <?php } ?>
              </div>

              <div class="row mt-5">
                <div class="col-md-12 text-center">
                  <nav aria-label="Page navigation" class="text-center">
                    <ul class="pagination">
                      <li class="page-item  active"><a class="page-link" href="#">&lt;</a></li>
                        <?php
                        for ($i=1;$i<$len;$i++){?>
                      <li class="page-item"><a class="page-link" href="<?=$url?>/question-answer/page/<?=$i?>"><?=$i?></a></li>
                        <?php }?>

                    </ul>
                  </nav>
                </div>
              </div>
            </div>

            <!-- END main-content -->

            <?php include 'component/questionleftbar.phtml'?>
              <!-- END sidebar-box -->


            <!-- END sidebar -->
          </div>
        </div>
      </section>

        <?php include 'component/footer.phtml'?>
      <!-- END footer -->

    </div>
    
    <!-- loader -->

<?php
include 'component/script.phtml'; ?>
  </body>
</html>